# Ordered manifest of all pending sidebar links (file order in app/index.html).
# Each entry: (section_key, human_title). The i-th pending anchor in index.html
# gets rewired to the i-th key here, once view-<key>.html exists.

MANIFEST = [
    # --- Learning Path: Building Blocks ---
    ("stylised-facts", "Stylised Facts of Asset Returns"),
    ("radon-nikodym", "Radon-Nikodym & Change of Measure"),
    ("kelly-criterion", "Kelly Criterion & Optimal Bet Sizing"),
    ("coin-tossing", "Coin-Tossing & Random Walk Limits"),
    # --- Quantitative Risk & Return ---
    ("capm-apt", "CAPM & Arbitrage Pricing Theory (APT)"),
    ("black-litterman", "Black-Litterman Model"),
    ("coherent-risk", "Coherent Risk Measures & Expected Shortfall"),
    ("arch-garch", "ARCH & GARCH Models"),
    ("egarch-gjr", "EGARCH & GJR-GARCH Extensions"),
    ("realized-implied-vol", "Realized vs. Implied Volatility Dynamics"),
    ("basel-accords", "Basel Accord Evolution (I to IV)"),
    ("collateral-ccp", "Collateral, Margins & Central Clearing (CCPs)"),
    # --- Equities, Currencies & Vanilla Options ---
    ("cost-of-carry", "Cost of Carry Framework (Black-76, Garman-Kohlhagen)"),
    ("historical-models", "Historical Models: Bachelier, Sprenkle, Boness"),
    ("greeks-first-order", "First-Order Greeks (Delta, Gamma, Theta, Vega, Rho)"),
    ("greeks-higher-order", "Higher-Order Greeks (Vanna, Volga, Charm, Color)"),
    ("early-exercise", "Why Analytical Solutions Fail for Early Exercise"),
    ("roll-geske-whaley", "Roll-Geske-Whaley Model"),
    ("baw-approximation", "Barone-Adesi & Whaley Quadratic Approximation"),
    ("bjerksund-stensland", "Bjerksund-Stensland (1993 & 2002)"),
    ("escrowed-dividend", "Escrowed Dividend Model"),
    ("implied-vol-solvers", "Implied Vol: Bisection, Newton-Raphson, Corrado-Miller"),
    # --- Numerical Methods & Data Science ---
    ("antithetic-control-variates", "Antithetic Variables & Control Variates"),
    ("ml-unsupervised", "Unsupervised Learning: K-Means & GMM Regime Detection"),
    ("ml-deep-nlp", "Deep Learning & NLP: LSTM & Sentiment Analysis"),
    ("ml-reinforcement", "Reinforcement Learning for Portfolio Management"),
    # --- Commodities, Energy & IR Derivatives ---
    ("black76-commodities", "Black '76 Model for Commodity Options"),
    ("spark-crack-spreads", "Spread Options: Spark & Crack Spreads"),
    ("swing-contracts", "Swing Contracts: Flexible Volume Take-up"),
    ("caps-floors-black", "Caps, Floors & Swaptions (Black Lognormal)"),
    # --- Exotic Options & Credit Risk ---
    ("binary-digital-options", "Binary / Digital Options (Rubinstein-Reiner)"),
    ("barrier-options", "Barrier Options: Down & Out, Up & In"),
    ("lookback-options", "Lookback Options (Goldman-Sosin-Gatto)"),
    ("asian-options", "Asian Options: Geometric & Arithmetic Approximations"),
    ("compound-chooser-options", "Compound & Chooser Options (Geske, Rubinstein)"),
    ("margrabe-exchange", "Exchange Options: Margrabe's Formula"),
    ("rainbow-options", "Rainbow Options: Min/Max of Two Assets (Stulz)"),
    ("basket-spread-options", "Basket & Spread Options (Kirk's Approximation)"),
    ("merton-jump-diffusion", "Merton Jump-Diffusion Model"),
    ("gram-charlier", "Gram-Charlier Expansion (Skew & Kurtosis Adjustments)"),
    ("merton-structural", "Merton Structural Default Model"),
    ("reduced-form-credit", "Reduced-Form Intensity Models"),
    ("cdo-copula", "CDO Pricing & Copula Correlation"),
    ("normal-cdf-approx", "Univariate Normal CDF Approximations"),
    ("bivariate-normal", "Bivariate Normal Distribution (Drezner, Genz)"),
    ("trivariate-normal", "Trivariate Normal Distribution"),
    # --- Structured Products ---
    ("sp-ppn", "Principal Protected Note (PPN)"),
    ("sp-capital-guaranteed", "Capital Guaranteed Note"),
    ("sp-reverse-convertible", "Classic Reverse Convertible (ZCB + Short Put)"),
    ("sp-barrier-reverse-convertible", "Barrier Reverse Convertible (BRC)"),
    ("sp-range-accrual", "Range Accrual Corridor Note"),
    ("sp-phoenix-autocallable", "Phoenix Autocallable Note"),
    ("sp-tarn", "Target Redemption Note (TARN)"),
    ("sp-worst-of-phoenix", "Worst-Of Autocallable Phoenix"),
    ("sp-outperformance", "Outperformance Note"),
    # --- Developer Desk ---
    ("dev-python-sandbox", "Live Python Sandbox (WebAssembly Notebook)"),
    ("dev-quantlib-export", "Model Code Export to QuantLib Python"),
    ("dev-api-docs", "Production API Documentation & Integration Hub"),
    ("dev-sdk-exporter", "SDK Code Exporter (C++ / Python / C# DLL)"),
    ("dev-json-schema", "Custom JSON Schema Generator"),
    ("dev-json-viewer", "JSON Input/Output Payload Viewer"),
    ("dev-code-export", "Code Export to Python Templates & Excel"),
    # --- Calibration & Risk Desk tools ---
    ("tool-hist-vol", "Historical Volatility Tracker"),
    ("tool-svi-fitter", "Implied Volatility Surface Fitter (SVI)"),
    ("tool-delta-gamma-hedge", "Delta-Gamma Dynamic Portfolio Hedging Simulator"),
    ("tool-correlation-matrix", "Multi-Asset Correlation Matrix Builder"),
    # --- Masterclass: Mathematical Methods in Financial Markets (14 parts) ---
    ("mm-p01", "Part 01: Number Sets, Mappings, Functions"),
    ("mm-p02", "Part 02: Polynomials, Implied Volatility & Complex Numbers"),
    ("mm-p03", "Part 03: Taylor Series Approximations"),
    ("mm-p04", "Part 04: Functional Integration Techniques"),
    ("mm-p05", "Part 05: Random Variables & Probability Moments"),
    ("mm-p06", "Part 06: Ordinary, Partial & Stochastic Differential Equations"),
    ("mm-p07", "Part 07: Solving First-Order ODEs with Boundary Values"),
    ("mm-p08", "Part 08: Cauchy-Euler Equations (Perpetual Option Solutions)"),
    ("mm-p09", "Part 09: Simulating Asset Randomness & Brownian Paths"),
    ("mm-p10", "Part 10: Ito's Lemma & Corrective Terms"),
    ("mm-p11", "Part 11: Lognormal Stock Price Evolution Derivation"),
    ("mm-p12", "Part 12: Short Rate Mechanics (Vasicek vs. CIR)"),
    ("mm-p13", "Part 13: Black-Scholes PDE Parabolic Framework"),
    ("mm-p14", "Part 14: Practical Stochastic Path Generation in Excel"),
    # --- Masterclass: Complex Analysis (17 parts) ---
    ("ca-p01", "Part 01: Complex Variable Integration & Holomorphic Motivation"),
    ("ca-p02", "Part 02: De Moivre's Theorem & Euler Integrals"),
    ("ca-p03", "Part 03: Geometric Moduli Interpretations"),
    ("ca-p04", "Part 04: Mapping z-Plane to w-Plane f(z)"),
    ("ca-p05", "Part 05: Holomorphic Functions & Power Series Convergence"),
    ("ca-p06", "Part 06: Cauchy-Riemann Differentiability Tests"),
    ("ca-p07", "Part 07: Harmonic Conjugates & Laplace Solutions"),
    ("ca-p08", "Part 08: Cauchy-Riemann Polar Coordinate Derivations"),
    ("ca-p09", "Part 09: Contour Parameterization & Complex Integration"),
    ("ca-p10", "Part 10: Cauchy's Integral Theorem"),
    ("ca-p11", "Part 11: Cauchy's Integral Formula with Singularity Splitting"),
    ("ca-p12", "Part 12: Definite Real Trigonometric Contour Evaluation"),
    ("ca-p13", "Part 13: Taylor vs. Laurent Expansions"),
    ("ca-p14", "Part 14: Classifying Singularities (Poles vs. Essential)"),
    ("ca-p15", "Part 15: Residue Theorem & Polynomial Contour Integration"),
    ("ca-p16", "Part 16: Infinite Real Domain Contour Integrals"),
    ("ca-p17", "Part 17: Infinite Definite Trigonometric Residue Evaluation"),
    # --- Masterclass: Intraday High-Frequency Trading (12 parts) ---
    ("hft-p01", "Part 01: Limit Order Books, Spreads & Liquidity Flows"),
    ("hft-p02", "Part 02: Market Impact Functions & Order Distribution"),
    ("hft-p03", "Part 03: Estimating Impact Models via Statistical Volatility"),
    ("hft-p04", "Part 04: Volume Distribution Modeling & Heavy-Tail Spikes"),
    ("hft-p05", "Part 05: Intraday Microstructure Seasonality Modeling"),
    ("hft-p06", "Part 06: Multi-Venue Trade Execution (Dark Pools vs Lit Markets)"),
    ("hft-p07", "Part 07: Transaction Cost Minimization Frameworks"),
    ("hft-p08", "Part 08: Volatility-Based Execution Optimization Algorithms"),
    ("hft-p09", "Part 09: Stock Diffusion Modeling with Numeric Boundaries"),
    ("hft-p10", "Part 10: Stochastic Control Theory & Trade Execution"),
    ("hft-p11", "Part 11: MATLAB High-Frequency Data Manipulation Labs"),
    ("hft-p12", "Part 12: Identifying Microstructure Price Relationships"),
    # --- Masterclass: Advanced Risk Management & Regulation (10 parts) ---
    ("arm-p01", "Part 01: Calibration & Modeling Risk Overview"),
    ("arm-p02", "Part 02: Multidisciplinary Risk Assessment Frameworks"),
    ("arm-p03", "Part 03: Non-Normal Distributions in Risk Assets"),
    ("arm-p04", "Part 04: Classic Risk Categorizations (Market, Credit, Liquidity, OpRisk)"),
    ("arm-p05", "Part 05: Calculating Value-at-Risk (VaR) via Historical Simulation"),
    ("arm-p06", "Part 06: Return Distribution Fat-Tail Realities"),
    ("arm-p07", "Part 07: Limitations of Classical VaR Measures"),
    ("arm-p08", "Part 08: Monte Carlo VaR Projection for Two Assets"),
    ("arm-p09", "Part 09: Excel Random Number Generators vs. Industry Standards"),
    ("arm-p10", "Part 10: Multi-Asset VaR Projection Mechanics"),
    # --- Masterclass: Introduction to Algorithmic Differentiation (11 parts) ---
    ("ad-p01", "Part 01: Source Code Transformation Principles"),
    ("ad-p02", "Part 02: Operator Overloading vs. Source-to-Source Compilers"),
    ("ad-p03", "Part 03: Elemental Operations Computation Graphs"),
    ("ad-p04", "Part 04: Implementing Manual Tangent Linear Code"),
    ("ad-p05", "Part 05: Tangent Linear Efficiency Tricks (Vector Mode & Sparsity)"),
    ("ad-p06", "Part 06: Adjoint Code Mechanics & Memory Constraints"),
    ("ad-p07", "Part 07: Adjoint Reverse Mode Implementation & Stacks"),
    ("ad-p08", "Part 08: Code Overloading for Backward Interpretation"),
    ("ad-p09", "Part 09: Automatic Code Generation Tools (Adjoint Applications)"),
    ("ad-p10", "Part 10: Second-Order Adjoints & Hessian Matrix Extraction"),
    ("ad-p11", "Part 11: Iterative Code Optimization & Performance Profiles"),
    # --- Masterclass: Asymptotics for Stochastic Volatility Models (8 parts) ---
    ("asv-p01", "Part 01: Hyperbolic Metrics & Heat Kernels in SABR Toy Models"),
    ("asv-p02", "Part 02: SABR Implied Volatility Smile Corrections"),
    ("asv-p03", "Part 03: Small-Time vs. Large-Time Asymptotic Limits"),
    ("asv-p04", "Part 04: SABR vs. CEV/Heston Large-Time Limit Comparisons"),
    ("asv-p05", "Part 05: Exponential Levy Option Asymptotics"),
    ("asv-p06", "Part 06: Share Measures & Small-Time Asymptotics"),
    ("asv-p07", "Part 07: CEV-Heston and Kou/CGMY Hybrid Frameworks"),
    ("asv-p08", "Part 08: Large Deviation Principles (LDP) in Option Pricing"),
    # --- Masterclass: Risk-Sensitive Investment Management (7 parts) ---
    ("rsi-p01", "Part 01: Stochastic Control Models in Asset Allocation"),
    ("rsi-p02", "Part 02: Risk-Sensitive Control vs. Mean-Variance Optimization"),
    ("rsi-p03", "Part 03: Fractional Kelly Capital Growth Strategies in Practice"),
    ("rsi-p04", "Part 04: Black-Litterman Benchmarking with Jumps"),
    ("rsi-p05", "Part 05: Asset Liability Management (ALM) Jump Diffusion"),
    ("rsi-p06", "Part 06: Stochastic Factor Asset/Liability Strategy Derivation"),
    ("rsi-p07", "Part 07: Finite vs. Infinite Horizon Optimization Practicality"),
    # --- Masterclass: misc ---
    ("fintech-workshop", "Fintech & Digital Asset Disruption Workshop"),
    ("gpu-monte-carlo", "Code Porting: GPU Acceleration of Monte Carlo (CVA & CCR)"),
    ("python-lab-workshop", "Python Lab Workshop (Code Submissions)"),
    ("portfolio-workshop", "Final Project Portfolio Workshop I & II"),
    # --- Thematic ---
    ("thematic-portal", "Search & Filter Portal (Browse All Parts)"),
    ("talk-ai-risk-management", "AI Revolution in Risk Management"),
    ("talk-ai-safety", "Behavioral Economics Approach to AI Safety"),
    ("talk-nlp-sdg", "Natural Language Processing for SDGs"),
    ("talk-llm-quant", "Customizing LLMs for Quant Finance Applications"),
    ("talk-sentiment-portfolios", "Beating Markowitz with Sentiment & Downside Control"),
    ("talk-trend-following", "De-constructing a Trend Following Trading System"),
    ("talk-crypto-lob", "Limit Order Book Flows and Price Formation in Crypto"),
    ("talk-kelly-ziemba", "Kelly Capital Growth Criterion & Its Applications"),
    ("talk-hrp", "Beating Markowitz with Hierarchical Risk Parity"),
    ("talk-max-diversification", "Robust Maximum Diversification Techniques"),
    ("talk-quantum-pricing", "A Quantum Finance Approach to Option Pricing"),
    ("talk-quantum-ml", "How Current Quantum Hardware Helps ML Tasks"),
    ("talk-quantum-economics", "Let's Do Quantum Economics!"),
    ("talk-day-portfolio-manager", "Day in the Life of a Quantitative Portfolio Manager"),
    ("talk-day-quant-trader", "Day in the Life of a Quant Trader"),
    ("talk-day-quant-auditor", "Day in the Life of a Quant Auditor"),
    ("talk-quant-interview", "Mastering the Quant Finance Interview"),
]

assert len(MANIFEST) == 167, len(MANIFEST)
assert len({k for k, _ in MANIFEST}) == 167, "duplicate keys"
